name: danger_zone_alert
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Dependencies
  # Provides animated typewriter text
  animated_text_kit: ^4.2.1
  # Wrapper to enable modal progress HUD
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # Customizable rating bar
  flutter_rating_bar: ^4.0.0
  # Wrapper around Inherited Widget
  provider: ^6.0.2
  # Display local notifications
  flutter_local_notifications: ^9.3.0
  # Customizable loading indicator
  flutter_spinkit: ^5.1.0
  # Customizable floating search bar
  material_floating_search_bar: ^0.3.6
  # Making http Requests
  http: ^0.13.4
  # Provide animation for list utility
  implicitly_animated_reorderable_list: ^0.4.2 # search bar animation
  # Allow the usage of News API
  news_api_flutter_package: ^1.1.0
  # Handles URL in the mobile platform
  url_launcher: ^6.0.20
  # Handles data visualization
  fl_chart: ^0.50.1
  # Customizable bottom navigation bar
  bottom_navy_bar: ^6.0.0
  # Customizable popup dialogs
  rflutter_alert: ^2.0.4
  # Data visualization library
  syncfusion_flutter_charts: ^20.1.47+1


  # List of Google Map Dependencies
  # Provides a Google Maps widgets
  google_maps_flutter: ^2.1.0
  # Provides geocoding & reverse geocoding services
  geocoding: ^2.0.1
  # Provides easy access to platform specific location services
  geolocator: ^8.0.5


  # Firebase Dependencies
  # Enables the connection of multiple firebase apps
  firebase_core: ^1.11.0
  # Allow the usage of Firebase Authentication API
  firebase_auth: ^3.3.5
  # Allows the usage of Cloud Firestore API
  cloud_firestore: ^3.1.6
  # Simply the store and query process of geographic location
  geoflutterfire: ^3.0.3 # geoPoint & geoHash

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Simplifies the task of updating app's launcher icon
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icon.png
    - assets/dataset.csv
